version: "3"

services:
    bastion:
        image: nginx
        container_name: bastion
        volumes:
            - ./bastion/:/etc/nginx/conf.d/
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_HOST=samela.io
            - NGINX_PORT=80
        restart: always

    plex:
        image: plexinc/pms-docker:plexpass
        container_name: plex
        network_mode: host
        restart: always
        environment:
            - TZ="America/Boston"
        devices:
            - /dev/dri:/dev/dri
        volumes:
            - /share/Library:/data:rw
        restart: always

    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        restart: always
        environment:
            - TZ="America/Boston"
        ports:
            - "192.168.1.5:53:53/tcp"
            - "192.168.1.5:53:53/udp"
            - "67:67/udp"
            - "8080:80/tcp"
            - "444:443/tcp"
        volumes:
            - ".pihole/etc-pihole/:/etc/pihole/"
            - ".pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
        cap_add:
            - NET_ADMIN
        restart: unless-stopped

    rtltcp:
        container_name: rtltcp
        image: kosdk/rtl-tcp
        ports:
            - 1234:1234
        devices: 
            - /dev/bus/usb/003
        restart: always

    samba:
        image: joebiellik/samba-server
        volumes:
            - ./smb.conf:/etc/samba/smb.conf
            - /share:/mnt/share
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/tcp"
            - "445:445/tcp"

    transmission:
        image: ghcr.io/linuxserver/transmission
        container_name: transmission
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Boston
            - TRANSMISSION_WEB_HOME=/transmission-web-control
        volumes:
            - /share/temp/downloads:/downloads
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        restart: unless-stopped

    minecraft:
        image: itzg/minecraft-server
        container_name: minecraft
        ports: 
            - "25565:25565"
        volumes:
            - "/minecraft:/data"
        environment:
            EULA: "TRUE"
        restart: always
    
    library:
        image: nginx
        container_name: library
        volumes:
            - /share/Library:/data
            - ./library/:/etc/nginx/conf.d/
            - ~/.htpasswd:/.htpasswd
        ports:
            - "1337:80"
        environment:
            - NGINX_HOST=samela.io
            - NGINX_PORT=80
        restart: always

    homeassistant:
        container_name: homeassistant
        image: homeassistant/home-assistant:stable
        volumes:
            - ./homeassistant:/config
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped
        network_mode: host

    beehive-weight-data-bridge:
        container_name: beehive-weight-data-bridge
        image: beehive-weight-data-bridge
        ports:
            - "8075:8075"
        volumes:
            - ./beehive-weight-data-bridge:/usr/src/app
        restart: unless-stopped

