version: "3"

services:
    bastion:
        image: nginx
        container_name: bastion
        ports:
            - "80"
            - "443"
        environment:
            - NGINX_HOST=samela.io
            - NGINX_PORT=80

    plex:
        image: plexinc/pms-docker:plexpass
        container_name: plex
        network_mode: host
        restart: always
        environment:
            - TZ="America/Boston"
        devices:
            - /dev/dri:/dev/dri
        volumes:
            - /share/Library:/data:rw
        restart: always

    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        restart: always
        environment:
            - TZ="America/Boston"
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            - "8080:80/tcp"
            - "443:443/tcp"
        volumes:
            - "./etc-pihole/:/etc/pihole/"
            - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
        cap_add:
            - NET_ADMIN

    rtltcp:
        container_name: rtltcp
        image: kosdk/rtl-tcp
        ports:
            - 1234:1234
        devices: 
            - /dev/bus/usb/003
        restart: always

    samba:
        image: joebiellik/samba-server
        volumes:
            - ./smb.conf:/etc/samba/smb.conf
            - /share:/mnt/share
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/tcp"
            - "445:445/tcp"

    transmission:
        image: gists/transmission
        container_name: transmission
        ports:
            - "9091:9091"
            - "51413:51413"
        environment:
            - USERNAME=admin
            - PASSWORD=admin
        volumes:
            - /share/temp:/data
        restart: always

    minecraft:
        image: itzg/minecraft-server
        container_name: minecraft
        ports: 
            - "25565:25565"
        volumes:
            - "/minecraft:/data"
        environment:
            EULA: "TRUE"
        restart: always

