version: "3"

services:
    bastion:
        image: nginx
        container_name: bastion
        ports:
            - "80"
            - "443"
        environment:
            - NGINX_HOST=samela.io
            - NGINX_PORT=80

    plex:
        image: plexinc/pms-docker:public
        container_name: plex
        network_mode: host
        restart: always
        environment:
            - TZ="America/Boston"
        devices:
            - /dev/dri:/dev/dri
        volumes:
            - /share/Library:/data:ro

    samba:
        image: joebiellik/samba-server
        volumes:
            - ./smb.conf:/etc/samba/smb.conf
            - /share:/mnt/share
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/tcp"
            - "445:445/tcp"

    transmission:
        image: gists/transmission
        container_name: transmission
        ports:
            - "9091:9091"
            - "51413:51413"
        volumes:
            - /share/temp:/data
        restart: always

    shinobi:
        image: shinobisystems/shinobi:latest-ubuntu
        container_name: shinobi
        ports: 
            - "8080:8080/tcp"
        environment:
            - APP_BRANCH=dev
        volumes:
            - /dev/shm/shinobiStreams:/dev/shm/streams:rw
            - $HOME/shinobiConfig:/config:rw
            - $HOME/shinobiCustomAutoLoad:/customAutoLoad:rw
            - $HOME/shinobiDatabase:/var/lib/mysql:rw
            - $HOME/shinobiVideos:/opt/shinobi/videos:rw
